-- phpMyAdmin SQL Dump
-- version 4.1.12
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Sep 11, 2015 at 09:44 PM
-- Server version: 5.6.16
-- PHP Version: 5.5.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `devotional`
--

-- --------------------------------------------------------

--
-- Table structure for table `devotion`
--

CREATE TABLE IF NOT EXISTS `devotion` (
  `did` int(4) NOT NULL AUTO_INCREMENT,
  `title` varchar(50) NOT NULL,
  `date` date NOT NULL,
  `verse` varchar(50) NOT NULL,
  `bible_reading` varchar(200) NOT NULL,
  `devotional_reading` varchar(1000) NOT NULL,
  `prayer` varchar(200) NOT NULL,
  PRIMARY KEY (`did`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=19 ;

--
-- Dumping data for table `devotion`
--

INSERT INTO `devotion` (`did`, `title`, `date`, `verse`, `bible_reading`, `devotional_reading`, `prayer`) VALUES
(1, 'Heaven is our future reality', '2015-09-09', 'Genesis 16: 1 -6', 'Lord has kept me from having children. Go to sleep with my maidservant, perhaps I can build my family through her. Genesis 16:2', 'I do not propose to examine this argument in detail, or to show the\nexact points where, in my opinion, it is fallacious. I have quoted it\nonly as an example of method. Most people will admit, I think, that it\nis calculated to produce bewilderment rather than conviction, because\nthere is more likelihood of error in a very subtle, abstract, and\ndifficult argument than in so patent a fact as the interrelatedness of\nthe things in the world. To the early Greeks, to whom geometry was\npractically the only known science, it was possible to follow reasoning\nwith assent even when it led to the strangest conclusions. But to us,\nwith our methods of experiment and observation, our knowledge of the\nlong history of _a priori_ errors refuted by empirical science, it has\nbecome natural to suspect a fallacy in any deduction of which the\nconclusion appears to contradict patent facts. It is easy to carry such\nsuspicion too far, and it is very desirable, if possible, actually to\ndiscover the ', 'But may I never boast except in the cross of our Lord Jesus Christ, though which the world has been crucified to me, and I to the world.'),
(4, 'Day is at Hand', '2015-09-08', 'Revelations 2: 28 - 30', 'Just as I have received the right to rule from Father and I will give in the morning star.', 'The following lectures[1] are an attempt to show, by means of examples,\r\nthe nature, capacity, and limitations of the logical-analytic method in\r\nphilosophy. This method, of which the first complete example is to be\r\nfound in the writings of Frege, has gradually, in the course of actual\r\nresearch, increasingly forced itself upon me as something perfectly\r\ndefinite, capable of embodiment in maxims, and adequate, in all branches\r\nof philosophy, to yield whatever objective scientific knowledge it is\r\npossible to obtain. Most of the methods hitherto practised have\r\nprofessed to lead to more ambitious results than any that logical\r\nanalysis can claim to reach, but unfortunately these results have always\r\nbeen such as many competent philosophers considered inadmissible.\r\nRegarded merely as hypotheses and as aids to imagination, the great\r\nsystems of the past serve a very useful purpose, and are abundantly\r\nworthy of study. But something different is required if philosophy is to\r\nbecome a sci', 'In Christ God was reconciling the world to himself, not counting peoples trespasses against them.'),
(5, 'He Refines them', '2015-09-07', 'Galatians 6 :14 - 17', 'But may I never toast except in the cross of our Lord Jesus Christ, through which the world has been crucified to me, and I to the world.', 'The following lectures[1] are an attempt to show, by means of examples,\r\nthe nature, capacity, and limitations of the logical-analytic method in\r\nphilosophy. This method, of which the first complete example is to be\r\nfound in the writings of Frege, has gradually, in the course of actual\r\nresearch, increasingly forced itself upon me as something perfectly\r\ndefinite, capable of embodiment in maxims, and adequate, in all branches\r\nof philosophy, to yield whatever objective scientific knowledge it is\r\npossible to obtain. Most of the methods hitherto practised have\r\nprofessed to lead to more ambitious results than any that logical\r\nanalysis can claim to reach, but unfortunately these results have always\r\nbeen such as many competent philosophers considered inadmissible.\r\nRegarded merely as hypotheses and as aids to imagination, the great\r\nsystems of the past serve a very useful purpose, and are abundantly\r\nworthy of study. But something different is required if philosophy is to\r\nbecome a sci', 'The one who tends a fig tree will eat its fruit, and whoever takes care of his master will honored.'),
(6, 'Win or Lose', '2015-09-10', '2 Timothy 4:1 - 8', 'I have fought the good fight, I have finished the  race, I have kept the faith  2 Timothy 4:7', 'I do not propose to examine this argument in detail, or to show the\r\nexact points where, in my opinion, it is fallacious. I have quoted it\r\nonly as an example of method. Most people will admit, I think, that it\r\nis calculated to produce bewilderment rather than conviction, because\r\nthere is more likelihood of error in a very subtle, abstract, and\r\ndifficult argument than in so patent a fact as the interrelatedness of\r\nthe things in the world. To the early Greeks, to whom geometry was\r\npractically the only known science, it was possible to follow reasoning\r\nwith assent even when it led to the strangest conclusions. But to us,\r\nwith our methods of experiment and observation, our knowledge of the\r\nlong history of _a priori_ errors refuted by empirical science, it has\r\nbecome natural to suspect a fallacy in any deduction of which the\r\nconclusion appears to contradict patent facts. It is easy to carry such\r\nsuspicion too far, and it is very desirable, if possible, actually to\r\ndiscover the ', 'I can always count on God, my heavenly Father, For he changes not; He is faithful.'),
(8, 'Virtuoso', '2015-09-11', '1 Corinthians 10:31-11:1', 'Therefor, whatever you do, do all to the glory of God.  1 Corinthians 10:31', 'I do not propose to examine this argument in detail, or to show the\r\nexact points where, in my opinion, it is fallacious. I have quoted it\r\nonly as an example of method. Most people will admit, I think, that it\r\nis calculated to produce bewilderment rather than conviction, because\r\nthere is more likelihood of error in a very subtle, abstract, and\r\ndifficult argument than in so patent a fact as the interrelatedness of\r\nthe things in the world. To the early Greeks, to whom geometry was\r\npractically the only known science, it was possible to follow reasoning\r\nwith assent even when it led to the strangest conclusions. But to us,\r\nwith our methods of experiment and observation, our knowledge of the\r\nlong history of _a priori_ errors refuted by empirical science, it has\r\nbecome natural to suspect a fallacy in any deduction of which the\r\nconclusion appears to contradict patent facts. It is easy to carry such\r\nsuspicion too far, and it is very desirable, if possible, actually to\r\ndiscover the ', 'The gift we offer to the Lord are by his standards measured; Our sacrifice and lives of praise.'),
(9, 'Who and How', '2015-09-12', 'Mark 8:27 - 33', 'You are the Christ. Mark 8:24', 'I do not propose to examine this argument in detail, or to show the\r\nexact points where, in my opinion, it is fallacious. I have quoted it\r\nonly as an example of method. Most people will admit, I think, that it\r\nis calculated to produce bewilderment rather than conviction, because\r\nthere is more likelihood of error in a very subtle, abstract, and\r\ndifficult argument than in so patent a fact as the interrelatedness of\r\nthe things in the world. To the early Greeks, to whom geometry was\r\npractically the only known science, it was possible to follow reasoning\r\nwith assent even when it led to the strangest conclusions. But to us,\r\nwith our methods of experiment and observation, our knowledge of the\r\nlong history of _a priori_ errors refuted by empirical science, it has\r\nbecome natural to suspect a fallacy in any deduction of which the\r\nconclusion appears to contradict patent facts. It is easy to carry such\r\nsuspicion too far, and it is very desirable, if possible, actually to\r\ndiscover the ', 'We say we love humanity, but can we really claim and a readiness to sacrifice.'),
(10, 'Anticipation', '2015-09-13', '1 Thess. 4:13 - 18', 'I will come again and receive you to myself. John 14:3', 'I do not propose to examine this argument in detail, or to show the\r\nexact points where, in my opinion, it is fallacious. I have quoted it\r\nonly as an example of method. Most people will admit, I think, that it\r\nis calculated to produce bewilderment rather than conviction, because\r\nthere is more likelihood of error in a very subtle, abstract, and\r\ndifficult argument than in so patent a fact as the interrelatedness of\r\nthe things in the world. To the early Greeks, to whom geometry was\r\npractically the only known science, it was possible to follow reasoning\r\nwith assent even when it led to the strangest conclusions. But to us,\r\nwith our methods of experiment and observation, our knowledge of the\r\nlong history of _a priori_ errors refuted by empirical science, it has\r\nbecome natural to suspect a fallacy in any deduction of which the\r\nconclusion appears to contradict patent facts. It is easy to carry such\r\nsuspicion too far, and it is very desirable, if possible, actually to\r\ndiscover the ', 'To behold his lovely face, and tell him how I love him'),
(11, 'Fearful tears', '2015-09-14', 'Revelation 5:1 - 12', 'So I wept much, because no one was found worthy to open and read the scroll. Revelations 5:4', 'I do not propose to examine this argument in detail, or to show the\r\nexact points where, in my opinion, it is fallacious. I have quoted it\r\nonly as an example of method. Most people will admit, I think, that it\r\nis calculated to produce bewilderment rather than conviction, because\r\nthere is more likelihood of error in a very subtle, abstract, and\r\ndifficult argument than in so patent a fact as the interrelatedness of\r\nthe things in the world. To the early Greeks, to whom geometry was\r\npractically the only known science, it was possible to follow reasoning\r\nwith assent even when it led to the strangest conclusions. But to us,\r\nwith our methods of experiment and observation, our knowledge of the\r\nlong history of _a priori_ errors refuted by empirical science, it has\r\nbecome natural to suspect a fallacy in any deduction of which the\r\nconclusion appears to contradict patent facts. It is easy to carry such\r\nsuspicion too far, and it is very desirable, if possible, actually to\r\ndiscover the ', 'Our lord is worthy all our days, of all our love and highest praise.'),
(12, 'God''s Flannelgraph', '2015-09-15', 'Psalm 19', 'The heavens declare the glory of God; and the firmament shows His handiwork. Psalm 19:1', 'I do not propose to examine this argument in detail, or to show the\r\nexact points where, in my opinion, it is fallacious. I have quoted it\r\nonly as an example of method. Most people will admit, I think, that it\r\nis calculated to produce bewilderment rather than conviction, because\r\nthere is more likelihood of error in a very subtle, abstract, and\r\ndifficult argument than in so patent a fact as the interrelatedness of\r\nthe things in the world. To the early Greeks, to whom geometry was\r\npractically the only known science, it was possible to follow reasoning\r\nwith assent even when it led to the strangest conclusions. But to us,\r\nwith our methods of experiment and observation, our knowledge of the\r\nlong history of _a priori_ errors refuted by empirical science, it has\r\nbecome natural to suspect a fallacy in any deduction of which the\r\nconclusion appears to contradict patent facts. It is easy to carry such\r\nsuspicion too far, and it is very desirable, if possible, actually to\r\ndiscover  ', 'With words of great power God formed the world-By the strength of His voice heaven''s hosts were unfurled;'),
(13, 'Forgetting Ourselves', '2015-09-16', 'Philippians 2:1 - 4', 'Let every man be swift to hear, slow to speak. James 1:19', 'I do not propose to examine this argument in detail, or to show the\r\nexact points where, in my opinion, it is fallacious. I have quoted it\r\nonly as an example of method. Most people will admit, I think, that it\r\nis calculated to produce bewilderment rather than conviction, because\r\nthere is more likelihood of error in a very subtle, abstract, and\r\ndifficult argument than in so patent a fact as the interrelatedness of\r\nthe things in the world. To the early Greeks, to whom geometry was\r\npractically the only known science, it was possible to follow reasoning\r\nwith assent even when it led to the strangest conclusions. But to us,\r\nwith our methods of experiment and observation, our knowledge of the\r\nlong history of _a priori_ errors refuted by empirical science, it has\r\nbecome natural to suspect a fallacy in any deduction of which the\r\nconclusion appears to contradict patent facts. It is easy to carry such\r\nsuspicion too far, and it is very desirable, if possible, actually to\r\ndiscover ', 'When may seem insignificant, Mundane, routine or small is often used by God to show'),
(14, 'Small things', '2015-09-17', 'John 6:4-14', 'There is a lad here who  has five barley loaves and two small fish, but what are they among so many.  John 6:9', 'I do not propose to examine this argument in detail, or to show the\r\nexact points where, in my opinion, it is fallacious. I have quoted it\r\nonly as an example of method. Most people will admit, I think, that it\r\nis calculated to produce bewilderment rather than conviction, because\r\nthere is more likelihood of error in a very subtle, abstract, and\r\ndifficult argument than in so patent a fact as the interrelatedness of\r\nthe things in the world. To the early Greeks, to whom geometry was\r\npractically the only known science, it was possible to follow reasoning\r\nwith assent even when it led to the strangest conclusions. But to us,\r\nwith our methods of experiment and observation, our knowledge of the\r\nlong history of _a priori_ errors refuted by empirical science, it has\r\nbecome natural to suspect a fallacy in any deduction of which the\r\nconclusion appears to contradict patent facts. It is easy to carry such\r\nsuspicion too far, and it is very desirable, if possible, actually to\r\ndiscover ', 'What may seem insignificant, mundane or routine or small is often used by God to show His overall power.'),
(15, 'Are we there yet', '2015-09-18', 'Deuteronomy 8:2', 'The lord your God led you all the way there forty years in wilderness, to humble you and test you, to know what was in your heart. Deut. 8:2', 'I do not propose to examine this argument in detail, or to show the\r\nexact points where, in my opinion, it is fallacious. I have quoted it\r\nonly as an example of method. Most people will admit, I think, that it\r\nis calculated to produce bewilderment rather than conviction, because\r\nthere is more likelihood of error in a very subtle, abstract, and\r\ndifficult argument than in so patent a fact as the interrelatedness of\r\nthe things in the world. To the early Greeks, to whom geometry was\r\npractically the only known science, it was possible to follow reasoning\r\nwith assent even when it led to the strangest conclusions. But to us,\r\nwith our methods of experiment and observation, our knowledge of the\r\nlong history of _a priori_ errors refuted by empirical science, it has\r\nbecome natural to suspect a fallacy in any deduction of which the\r\nconclusion appears to contradict patent facts. It is easy to carry such\r\nsuspicion too far, and it is very desirable, if possible, actually to\r\ndiscover ', 'All God''s testings have a purpose. Someday you will see the light , all He asks is that you trust him.'),
(17, 'Five-Minute Rule', '2015-09-19', 'Psalm 102:1 - 17', 'He shall regard the prayer of the destitute and shall not despise their prayer. Psalm 102:17', 'I do not propose to examine this argument in detail, or to show the\r\nexact points where, in my opinion, it is fallacious. I have quoted it\r\nonly as an example of method. Most people will admit, I think, that it\r\nis calculated to produce bewilderment rather than conviction, because\r\nthere is more likelihood of error in a very subtle, abstract, and\r\ndifficult argument than in so patent a fact as the interrelatedness of\r\nthe things in the world. To the early Greeks, to whom geometry was\r\npractically the only known science, it was possible to follow reasoning\r\nwith assent even when it led to the strangest conclusions. But to us,\r\nwith our methods of experiment and observation, our knowledge of the\r\nlong history of _a priori_ errors refuted by empirical science, it has\r\nbecome natural to suspect a fallacy in any deduction of which the\r\nconclusion appears to contradict patent facts. It is easy to carry such\r\nsuspicion too far, and it is very desirable, if possible, actually to\r\ndiscover ', 'The issue isn''t how much time we spend with God in prayer. But seeking Him throughout each day and knowing that He''s there.'),
(18, 'The Overflow', '2015-09-20', 'Psalm 103:1 - 10', 'Forget not all His benefits. Psalm 103:2', 'I do not propose to examine this argument in detail, or to show the\r\nexact points where, in my opinion, it is fallacious. I have quoted it\r\nonly as an example of method. Most people will admit, I think, that it\r\nis calculated to produce bewilderment rather than conviction, because\r\nthere is more likelihood of error in a very subtle, abstract, and\r\ndifficult argument than in so patent a fact as the interrelatedness of\r\nthe things in the world. To the early Greeks, to whom geometry was\r\npractically the only known science, it was possible to follow reasoning\r\nwith assent even when it led to the strangest conclusions. But to us,\r\nwith our methods of experiment and observation, our knowledge of the\r\nlong history of _a priori_ errors refuted by empirical science, it has\r\nbecome natural to suspect a fallacy in any deduction of which the\r\nconclusion appears to contradict patent facts. It is easy to carry such\r\nsuspicion too far, and it is very desirable, if possible, actually to\r\ndiscover.', 'We''re loaded with benefits daily, sent down from the Father above. His mercies and blessings abounding .');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
